#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path

from catalog_index import build_catalog_definitions, collect_skills


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate build-time catalog definition artifacts from scanned catalog manifests."
    )
    parser.add_argument(
        "--csharp-output",
        type=Path,
        required=True,
        help="Write a generated C# definitions file to this path.",
    )
    return parser.parse_args()


def escape_csharp_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def render_csharp_array(values: list[str], indent: str = "        ") -> str:
    if not values:
        return "[]"

    lines = ["["]
    lines.extend(f'{indent}"{escape_csharp_string(value)}",' for value in values)
    lines.append("    ]")
    return "\n".join(lines)


def render_csharp(definitions: dict[str, list[str]]) -> str:
    category_order = render_csharp_array(definitions["categories"])
    type_directories = render_csharp_array(definitions["typeDirectories"])

    return f"""// <auto-generated />
namespace ManagedCode.DotnetSkills.Runtime;

internal static class CatalogGeneratedDefinitions
{{
    public static string[] CategoryOrder {{ get; }} =
    {category_order};

    public static string[] TypeDirectories {{ get; }} =
    {type_directories};
}}
"""


def main() -> int:
    args = parse_args()
    skills = collect_skills()
    definitions = build_catalog_definitions(skills)

    output_path = args.csharp_output.resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_csharp(definitions), encoding="utf-8")

    print(
        f"Generated catalog definitions with {len(definitions['categories'])} categories "
        f"and {len(definitions['typeDirectories'])} type directories at {output_path}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
